[package]
name = "aicli"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3"
ratatui = "0.30.0"
tokio = { version = "1", features = ["full"] }
rag = { path = "rag" }
